config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :prodects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prodect.rb
class Prodect < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prodects_controller.rb
class ProdectsController < ApplicationController
  before_action :set_prodect, only: %i[ show edit update destroy ]

  # GET /prodects or /prodects.json
  def index
    @prodects = Prodect.all
  end

  # GET /prodects/1 or /prodects/1.json
  def show
  end

  # GET /prodects/new
  def new
    @prodect = Prodect.new
  end

  # GET /prodects/1/edit
  def edit
  end

  # POST /prodects or /prodects.json
  def create
    @prodect = Prodect.new(prodect_params)

    respond_to do |format|
      if @prodect.save
        format.html { redirect_to @prodect, notice: "Prodect was successfully created." }
        format.json { render :show, status: :created, location: @prodect }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prodect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prodects/1 or /prodects/1.json
  def update
    respond_to do |format|
      if @prodect.update(prodect_params)
        format.html { redirect_to @prodect, notice: "Prodect was successfully updated." }
        format.json { render :show, status: :ok, location: @prodect }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prodect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prodects/1 or /prodects/1.json
  def destroy
    @prodect.destroy
    respond_to do |format|
      format.html { redirect_to prodects_url, notice: "Prodect was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prodect
      @prodect = Prodect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prodect_params
      params.require(:prodect).permit(:name, :price, :vendor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prodects_helper.rb
module ProdectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductRegister</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prodects/_form.html.erb
<%= form_with(model: prodect, local: true) do |form| %>
  <% if prodect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prodect.errors.count, "error") %> prohibited this prodect from being saved:</h2>

      <ul>
      <% prodect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :vendor %>
    <%= form.text_field :vendor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prodects/edit.html.erb
<h1>Editing Prodect</h1>

<%= render 'form', prodect: @prodect %>

<%= link_to 'Show', @prodect %> |
<%= link_to 'Back', prodects_path %>

app/views/prodects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prodects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prodects.each do |prodect| %>
      <tr>
        <td><%= prodect.name %></td>
        <td><%= prodect.price %></td>
        <td><%= prodect.vendor %></td>
        <td><%= link_to 'Show', prodect %></td>
        <td><%= link_to 'Edit', edit_prodect_path(prodect) %></td>
        <td><%= link_to 'Destroy', prodect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prodect', new_prodect_path %>

app/views/prodects/new.html.erb
<h1>New Prodect</h1>

<%= render 'form', prodect: @prodect %>

<%= link_to 'Back', prodects_path %>

app/views/prodects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prodect.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @prodect.price %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @prodect.vendor %>
</p>

<%= link_to 'Edit', edit_prodect_path(@prodect) %> |
<%= link_to 'Back', prodects_path %>